// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjvsmdhnpahqbatjmpyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqdnNtZGhucGFocWJhdGptcHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MjgxOTQsImV4cCI6MjA1NTAwNDE5NH0.3VHpfFpWEmdgJUBfuBl4mJ5JHD-zxkUGlqXGB2yPOHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);